Repository lazybytez/jojo-discord-bot, pull requests merged in 2022-07, with the labels that each got.

#10 Setup GO project
  go.mod
  main.go
Labels: C2 - feature

#11 Install discordgo as dependency
  go.mod
  go.sum
Labels: C2 - feature

#12 Install zereolog dependency
  go.mod
  go.sum
Labels: C3 - enhancement

#14 Run tests during continues integration
  .github/workflows/ci.yml
Labels: C2 - feature

#15 Update readme
  README.md
Labels: C4 - documentation

#17 Update gitignore
  .env.example
  .gitignore
Labels: C2 - feature, C3 - enhancement

#19 Add production ready Docker image and image deployment
  .github/workflows/cd.yml
  Dockerfile
  scripts/entrypoint.sh
Labels: C2 - feature

#20 Add project structure and scopes
  README.md
  api/.keep
  commitlint.config.js
  component/.keep
  internal/.keep
Labels: C2 - feature, C3 - enhancement, C4 - documentation

#23 Implement simple component system
  .env.example
  README.md
  api/.keep
  api/component.go
  api/log/log.go
  component/.keep
  components/component_registry.go
  components/pingpong/pingpong.go
  go.mod
  go.sum
  internal/.keep
  internal/bootstrap.go
  internal/discordgo.go
  internal/env.go
  internal/quit.go
  main.go
Labels: C2 - feature

#28 Implement component based logging
  api/component.go
  api/log.go
  api/log/log.go
  components/component_registry.go
  components/pingpong/pingpong.go
Labels: C2 - feature

#34 Add CODEOWNERS file
  .github/CODEOWNERS
Labels: C2 - feature

#35 Add github action for code scanning
  .github/workflows/codeql-analysis.yml
Labels: C2 - feature

#36 Add dependabot auto updates for go modules
  .github/dependabot.yml
Labels: C2 - feature, C3 - enhancement

#37 Add security policy
  SECURITY.md
Labels: C2 - feature, C3 - enhancement
