Repository lazybytez/jojo-discord-bot, pull requests merged in 2022-10, with the labels that each got.

#97 Replace dependabot with renovate
  .github/dependabot.yml
  .github/renovate.json
  .github/workflows/git.yml
Labels: C2 - feature, C3 - enhancement

#104 Add possibility to retrieve version
  .github/workflows/deploy_edge.yml
  .github/workflows/deploy_release.yml
  Dockerfile
  Makefile
  build/version.go
  build/version_test.go
  components/statistics/command.go
Labels: C2 - feature

#108 Add Swagger for the WebAPI
  .env.example
  .github/workflows/ci.yml
  .gitignore
  Dockerfile
  Makefile
  components/statistics/collector.go
  components/statistics/command.go
  components/statistics/webapi.go
  core_components/bot_webapi/components.go
  go.mod
  go.sum
  internal/component_manager.go
  internal/env.go
  internal/webapi.go
  main.go
Labels: C2 - feature

#109 Ensure basepath is properly used
  internal/webapi.go
Labels: C1 - bug

#110 Finish final deployment for the bot
  .env.example
  .github/workflows/deploy_edge.yml
  .github/workflows/deploy_release.yml
  Dockerfile
  internal/database.go
  internal/env.go
Labels: C3 - enhancement

#111 Add zero-downtime deployment checks
  Dockerfile
Labels: C3 - enhancement

#112 Change wording in CODEOWNERS file
  .github/CODEOWNERS
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy_edge.yml
  .github/workflows/git.yml
  README.md
Labels: C3 - enhancement

#115 Define step id for build step
  .github/workflows/deploy_release.yml
Labels: C1 - bug
