Repository lazybytez/jojo-discord-bot, pull requests merged in 2022-09, with the labels that each got.

#73 Add codecov and go ref badge
  .gitignore
  Makefile
  README.md
Labels: C3 - enhancement, C4 - documentation

#74 Add tests for the database API
  api/component.go
  api/components/bot_core/command/module/list.go
  api/components/bot_core/guild_management.go
  api/database.go
  api/database/database.go
  api/database/database_mock_test.go
  api/database/database_test.go
  api/database/entities.go
  api/database/entities_test.go
  api/database/global_component_status.go
  api/database/guild.go
  api/database/guild_component_status.go
  api/database/registered_component.go
  go.mod
  go.sum
Labels: C3 - enhancement

#77 Add dice component
  api/cache/cache_test.go
  components/component_registry.go
  components/dice/command.go
  components/dice/command_test.go
  components/dice/create_answer.go
  components/dice/create_answer_test.go
  components/dice/create_message_embed.go
  components/dice/create_message_embed_test.go
  components/dice/dice.go
  components/dice/dice_test.go
  components/dice/register_command.go
Labels: C2 - feature
